set background=dark
set cindent
set encoding=utf8
set fileencoding=utf8
set fileencodings=ucs-bom,utf8,cp950,latin1
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set nobomb
set nocompatible
set number
set ruler
set scrolloff=3
set secure
set showmatch
set smartcase
set t_Co=256
set visualbell
set wildmenu
syntax on
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
