set background=dark
set cindent
set encoding=utf8
set fileencoding=utf8
set fileencodings=ucs-bom,utf8,cp950,latin1
set hlsearch
set ignorecase
set incsearch
set nobomb
set nocompatible
set ruler
set scrolloff=3
set secure
set smartcase
set t_Co=256
syntax on
