"
set autoindent
set backspace=indent,eol,start
set cursorline
set encoding=utf8
set expandtab
set fileencoding=utf8
set fileencodings=ucs-bom,utf8,cp950,gbk,latin1
set guifont=Inconsolata:h12
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set list
set listchars=tab:▷⋅,trail:·
set nobomb
set nocompatible
set nofoldenable
set number
set relativenumber
set ruler
set scrolloff=3
set secure
set shiftwidth=4
set showmatch
set smartcase
set t_Co=256
set visualbell
set wildmenu
syntax on
"
" color schema
let g:airline_powerline_fonts = 1
set background=dark
colo Tomorrow-Night-Eighties
highlight Search cterm=none ctermbg=blue
"
" mapping
map q: :q
nmap <Esc>[Z <C-w>W
nmap <F8> :TagbarToggle<CR>
nmap <Tab> <C-w>w
nnoremap <silent> p p`]
vmap <C-v> <Plug>(expand_region_shrink)
vmap v <Plug>(expand_region_expand)
vnoremap <silent> p p`]
vnoremap <silent> y y`]
"
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
"
Bundle "gmarik/vundle"
"
Bundle "airblade/vim-gitgutter"
Bundle "bling/vim-airline"
Bundle "bonsaiben/bootstrap-snippets"
Bundle "derekwyatt/vim-scala"
Bundle "elzr/vim-json"
Bundle "evidens/vim-twig"
Bundle "garbas/vim-snipmate"
Bundle "gregsexton/gitv"
Bundle "honza/vim-snippets"
Bundle "kien/ctrlp.vim"
Bundle "majutsushi/tagbar"
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "motus/pig.vim"
Bundle "nathanaelkane/vim-indent-guides"
Bundle "pangloss/vim-javascript"
Bundle "terryma/vim-expand-region"
Bundle "tomtom/tlib_vim"
Bundle "tpope/vim-fugitive"
"
filetype plugin indent on
let g:ctrlp_use_caching = 0
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
let g:SuperTabDefaultCompletionType = "context"
let g:vim_json_syntax_conceal = 0
let mapleader="\<Space>"
"
" other
au BufNewFile,BufRead *.go set filetype=go
au BufNewFile,BufRead *.sls set filetype=yaml
au BufNewFile,BufRead *.sls set shiftwidth=2
au BufNewFile,BufRead *.mk set noexpandtab
au BufNewFile,BufRead *.psgi setf perl
au BufNewFile,BufRead Makefile set noexpandtab
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
