"
set autoindent
set backspace=indent,eol,start
set cursorline
set encoding=utf8
set expandtab
set fileencoding=utf8
set fileencodings=ucs-bom,utf8,cp950,latin1
set guifont=Inconsolata:h12
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set list
set listchars=tab:▷⋅,trail:·
set nobomb
set nocompatible
set nofoldenable
set number
set ruler
set scrolloff=3
set secure
set shiftwidth=4
set showmatch
set smartcase
set t_Co=256
set visualbell
set wildmenu
syntax on
"
" color schema
let g:airline_powerline_fonts = 1
let g:solarized_termcolors = 256
colo solarized
set background=dark
highlight Search cterm=none ctermbg=blue
"
" keybinding
nmap <Esc>[Z <C-w>W
nmap <Tab> <C-w>w
nmap <F8> :TagbarToggle<CR>
"
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
"
Bundle "gmarik/vundle"
"
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "airblade/vim-gitgutter"
Bundle "bling/vim-airline"
Bundle "bonsaiben/bootstrap-snippets"
Bundle "ervandew/supertab"
Bundle "garbas/vim-snipmate"
Bundle "gregsexton/gitv"
Bundle "honza/vim-snippets"
Bundle "kien/ctrlp.vim"
Bundle "majutsushi/tagbar"
Bundle "motemen/git-vim"
Bundle "nathanaelkane/vim-indent-guides"
Bundle "tomtom/tlib_vim"
Bundle "tpope/vim-fugitive"
"
filetype plugin indent on
let g:SuperTabDefaultCompletionType = "context"
"
" other
au BufNewFile,BufRead *.go set filetype=go
au BufNewFile,BufRead *.json setf json
au BufNewFile,BufRead *.mk set noexpandtab
au BufNewFile,BufRead *.psgi setf perl
au BufNewFile,BufRead Makefile set noexpandtab
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
